-- sql문 변경 이력 관리 파일

CREATE TABLE todos
(
    todos_id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '일정 식별자',
    user_name VARCHAR(50) NOT NULL COMMENT '일정 작성자 이름',
    title VARCHAR(100) NOT NULL COMMENT '일정 제목',
    content TEXT NOT NULL COMMENT '일정 내용',
    create_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '생성일',
    edit_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL COMMENT '수정일'
);